security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    will:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    dave:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
      login_firewall:
              pattern:   ^/login$
              anonymous: ~

      secured_area:
              pattern:    ^/
              anonymous: ~
              http_basic:
                   realm: "Secured Search Area"
              form_login:
                  login_path: login
                  check_path: login_check
                  csrf_provider: form.csrf_provider
              logout:
                  path:   /logout
                  target: /


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
